CourseApplication/Areas/Admin/Controllers/CourseController.cs
using AutoMapper;
using courseApplication.Models;
using courseApplication.Services;
using CourseApplication.Data;
using CourseApplication.Models;
using CourseApplication.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseApplication.Areas.Admin.Controllers
{
    [Authorize(Roles ="Admin")]
    public class CourseController : Controller
    {
        private readonly IMapper mapper;
        private readonly CourseService courseService;
        private readonly CategoryService categoryService;
        private readonly TrainerService trainerService;
        public CourseController()
        {
            mapper = AutoMapperConfig.Mapper;
            courseService = new CourseService();
            categoryService = new CategoryService();
            trainerService = new TrainerService();
        }
        // GET: Admin/Course
        public ActionResult Index( string query = null,int? categoryId = null,int? trainerId = null)
        {
            var coursesListData = new CourseListModel();
            init(ref coursesListData);
            var coursesList = courseService.ReadAll(query,trainerId,categoryId);
            var mappedCuorsesList = mapper.Map<List<CourseModel>>(coursesList);
            coursesListData.Courses = mappedCuorsesList;

            return View(coursesListData);
        }

        public ActionResult Create()
        {
            var courseModel = new CourseModel();
            init(ref courseModel);
            return View(courseModel);
        }
        [HttpPost]
        public ActionResult Create(CourseModel courseData)
        {
            init(ref courseData);
          
            try
            {
                if(ModelState.IsValid)
                {
                    courseData.Image_ID = SaveImageFile(courseData.ImageFile);

                    var courseDTO = mapper.Map<Course>(courseData);
                    courseDTO.Category = null;
                    courseDTO.Trainer = null;
                  
                    var result = courseService.Create(courseDTO);
                    if (result >= 1)
                    {
                        return RedirectToAction("Index");
                    }
                    ViewBag.Message = "An error accourd!";
                }
                return View(courseData);

            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(courseData);
               
            }
            
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var currentCourseData = courseService.GetById(id.Value);
            var courseModel = mapper.Map<CourseModel>(currentCourseData);
            init(ref courseModel);
            return View(courseModel);
        }
        [HttpPost]
        public ActionResult Edit(CourseModel courseData)
        {
            init(ref courseData);
            
            try
            {
                if (ModelState.IsValid)
                {

                    courseData.Image_ID = SaveImageFile(courseData.ImageFile,courseData.Image_ID);
                    var courseDTO = mapper.Map<Course>(courseData);
                    courseDTO.Category = null;
                    courseDTO.Trainer = null;

                    var result = courseService.Update(courseDTO);
                    if (result >= 1)
                    {
                        return RedirectToAction("Index");
                    }
                    ViewBag.Message = "An error accourd!";
                }
                return View(courseData);

            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(courseData);

            }

        }

        private void init(ref CourseModel courseModel)
        {
            var mappedCategoriesList = GetCategories();
            courseModel.Categories = new SelectList(mappedCategoriesList, "Id", "Name");

            var mappedTrainersList = GetTrainers();
            courseModel.Trainers = new SelectList(mappedTrainersList, "Id", "Name");
        }

        private void init(ref CourseListModel coursesList)
        {

            var mappedCategoriesList = GetCategories();
            coursesList.Categories = new SelectList(mappedCategoriesList, "Id", "Name");

            var mappedTrainersList = GetTrainers();
            coursesList.Trainers = new SelectList(mappedTrainersList, "Id", "Name");
        }

        private IEnumerable<categoryModel> GetCategories()
        {
            var categories = categoryService.ReadAll(); 
            return mapper.Map<IEnumerable<categoryModel>>(categories);
        }

        private IEnumerable<TrainerModel> GetTrainers()
        {
            var trainers = trainerService.ReadAll();
            return mapper.Map<IEnumerable<TrainerModel>>(trainers);

        }

        private string SaveImageFile(HttpPostedFileBase imageFile,string currentImageId ="")
        {
            if (imageFile != null)
            {
                var fileExtension = Path.GetExtension(imageFile.FileName);
                var imageGuid = Guid.NewGuid().ToString();
                string imageId = imageGuid + fileExtension;

                // Save File
                var filePath = Server.MapPath($"~/Uploads/Courses/{imageId}");
                imageFile.SaveAs(filePath);

                // Delet Old File - Update Action
                if (!string.IsNullOrEmpty(currentImageId))
                {
                    string oldFilePath = Server.MapPath($"~/Uploads/Courses/{currentImageId}");
                    System.IO.File.Delete(oldFilePath);
                }
                return imageId;
            }
            return currentImageId;
        }
    }
}

CourseApplication/Areas/Admin/Controllers/CourseUnitsController.cs
using AutoMapper;
using CourseApplication.Data;
using CourseApplication.Models;
using CourseApplication.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseApplication.Areas.Admin.Controllers
{
    public class CourseUnitsController : Controller
    {
        private readonly IMapper mapper;
        private readonly CourseUnitService courseUnitService;
        public CourseUnitsController()
        {
            mapper = AutoMapperConfig.Mapper;
            courseUnitService = new CourseUnitService();
        }
        // GET: Admin/CourseUnits?courseId
        public ActionResult Index(int? courseId)
        {
            if (courseId == null)
            {
                return HttpNotFound();
            }
            var units = courseUnitService.ReadCourseUnits(courseId.Value);
            var mappedUnits = mapper.Map<IEnumerable<Course_Uints>, IEnumerable<CourseUnitsModel>>(units);
            ViewBag.courseName = mappedUnits.FirstOrDefault()?.Name;
            return View(mappedUnits);
        }

        // GET: Admin/CourseUnits/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/CourseUnits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/CourseUnits/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/CourseUnits/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/CourseUnits/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/CourseUnits/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/CourseUnits/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CourseApplication/Areas/Admin/Controllers/TraineeController.cs
using AutoMapper;
using CourseApplication.Data;
using CourseApplication.Models;
using CourseApplication.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseApplication.Areas.Admin.Controllers
{
    [Authorize(Roles ="Admin")]
    public class TraineeController : Controller
    {
        private readonly TraineeCourseService traineeCourseService;
        private readonly IMapper mapper;
        public TraineeController()
        {
            traineeCourseService = new TraineeCourseService();
            mapper = AutoMapperConfig.Mapper;
        }
        // GET: Admin/Trainee
        public ActionResult Index(int? CId)
        {
            if(CId == null)
            {
                return RedirectToAction("Index", "Default", new { area = "Admin" });
            }
            var trainees = traineeCourseService.GetTrainees(CId.Value);

            var courseTrainees = mapper.Map<IEnumerable<Trainee_Courses>, IEnumerable<TraineeCourseModel>>(trainees);
            return View(courseTrainees);
        }
    }
}

CourseApplication/Controllers/CourseController.cs
using AutoMapper;
using CourseApplication.Data;
using CourseApplication.Models;
using CourseApplication.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseApplication.Controllers
{
    public class CourseController : Controller
    {
        private readonly IMapper mapper;
        private readonly CourseService courseService;

        public CourseController()
        {
            mapper = AutoMapperConfig.Mapper;
            courseService = new CourseService();
        }
        // GET: Course
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Info(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return HttpNotFound("Course Not Found");
            }
            var courseInfo = courseService.GetById(Id.Value);
            if (courseInfo == null)
            {
                return HttpNotFound("Course Not Found");
            }
            var mappedcourseInfo = mapper.Map<Course, CourseModel>(courseInfo);
            return View(mappedcourseInfo);
        }

        public ActionResult Subscribe(int id)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account", new { returnUrl = $"/Course/Subscribe/{id}" });
            }
            return View();
        }
    }
}

CourseApplication/Areas/Admin/Views/Course/Create.cshtml
@model CourseApplication.Models.CourseModel

@{
    ViewBag.Title = "Add Course";
}

<h2>Add Course</h2>

@using (Html.BeginForm("Create","Course",FormMethod.Post,new {enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category_Id,Model.Categories ,new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.Trainer_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Trainer_Id,Model.Trainers,new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Trainer_Id, "", new { @class = "text-danger" })
            </div>
        </div>

     
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" id="ImageFile" />
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CourseApplication/Areas/Admin/Views/Course/Edit.cshtml
@model CourseApplication.Models.CourseModel

@{
    ViewBag.Title = "Update Course";
}

<h2>Update Course</h2>

@using (Html.BeginForm("Edit","Course",FormMethod.Post,new {enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Image_ID)
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Creation_Date)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category_Id,Model.Categories ,new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.Trainer_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Trainer_Id,Model.Trainers,new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Trainer_Id, "", new { @class = "text-danger" })
            </div>
        </div>

     
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" id="ImageFile" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Changes" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CourseApplication/Areas/Admin/Views/Course/Index.cshtml
@model CourseApplication.Models.CourseListModel

@{
    ViewBag.Title = "Courses";
}

<h2>Courses</h2>

<hr />
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Course", FormMethod.Get, new { @class = "form-inline" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Query)&nbsp;
        @Html.TextBoxFor(m => m.Query, new { @class = "form-control" })&nbsp;
    </div>
    
    <div class="form-group">
        @Html.LabelFor(m => m.TrainerId)&nbsp;
        @Html.DropDownListFor(c => c.TrainerId, Model.Trainers, "--Select Trainer--", new { @class = "form-control" })&nbsp;
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CategoryId)&nbsp;
        @Html.DropDownListFor(c => c.CategoryId, Model.Categories, "--Select Category--", new { @class = "form-control" })&nbsp;
    </div>

    <input type="submit" value="Search" class="btn btn-primary"/>
}

<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Courses.First().Image_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Courses.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Courses.First().Creation_Date)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Courses.First().Category_Name)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Courses.First().TrainerName)
        </th>
        <th>
            Trainees
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model.Courses) {
    <tr>
        <td>
            <img src="~/Uploads/Courses/@item.Image_ID" style="width: 75px" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Creation_Date)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Category_Name)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.TrainerName)
        </td>
        <td>
            @Html.ActionLink("Trainees", "Index", "Trainee", new { CId = item.ID},new { @class = "btn btn-primary"})
        </td>
      
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Contents", "Index", "CourseUnits", new { courseId=item.ID }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>